##
# Global Configurations.

spawns:
    kittens:
        untamed: false
#        dontAge: false
#        ageWhenClaimed: true
    puppies:
        untamed: false
#        dontAge: false
#        ageWhenClaimed: true
unclaimWith:
    cats: 350
    dogs: 287

avoidbugs: false

##
# Economy section.

enableEconomy: false
costs:
    ##
    # Cost to unclaim a pet the user owns.
    unclaim:
        cats: 0
        dogs: 0
    ##
    # Kickback to original owner when pet is adopted.
    reimburse:
        cats: 0
        dogs: 0
    ##
    # Cost to adopt a previously owned pet.
    adopt:
        ocelots: 0
        wolves: 0
    ##
    # Cost to tame an animal which has never been claimed before.
    tame:
        ocelots: 0
        wolves: 0
