name: AdoptAFuzz
version: 0.2
main: com.etherelements.hereinplainsight.AdoptAFuzz.AdoptAFuzz
author: HereInPlainSight
softdepend: [Vault]
license: Beerware (But with a milkshake!)
description: >
             Control the ownership of pets naturally without commands.
commands:
  adoptafuzz:
    description: Reloads the AdoptAFuzz configuration file.
    usage: /command

permissions:
    adoptafuzz.*:
        description: Gives access to all things adoptafuzz.
        default: op
        children:
            adoptafuzz.commands.*: true
            adoptafuzz.free.*: true
            adoptafuzz.ocelots.*: true
            adoptafuzz.wolves.*: true
    adoptafuzz.command.*:
        description: Gives access to adoptafuzz commands.
        default: false
        children:
            adoptafuzz.commands.reload: false
    adoptafuzz.ocelots.*:
        description: Gives access to all ocelot permissions.
        default: false
        children:
            adoptafuzz.ocelots.unclaim: false
    adoptafuzz.wolves.*:
        description: Gives access to all wolf permissions.
        default: false
        children:
            adoptafuzz.wolves.unclaim: false
    adoptafuzz.free.*:
        description: Gives free unclaims.
        default: false
        children:
            adoptafuzz.free.economy.*: false
            adoptafuzz.free.item.*: false
    adoptafuzz.free.economy.*:
        description: Gives free everything for economy users.
        default: false
        children:
            adoptafuzz.free.economy.adopt.*: false
            adoptafuzz.free.economy.tame.*: false
            adoptafuzz.free.economy.unclaim.*: false
    adoptafuzz.free.economy.adopt.*:
        description: Gives free adoptions for economy users.
        default: false
        children:
            adoptafuzz.free.economy.adopt.ocelots: false
            adoptafuzz.free.economy.adopt.wolves: false
    adoptafuzz.free.economy.tame.*:
        description: Gives free taming (of wild, never-before-tamed animals) for economy users.
        default: false
        children:
            adoptafuzz.free.economy.tame.ocelots: false
            adoptafuzz.free.economy.tame.wolves: false
    adoptafuzz.free.economy.unclaim.*:
        description: Gives free unclaims to economy users.
        default: false
        children:
            adoptafuzz.free.economy.unclaim.ocelots: false
            adoptafuzz.free.economy.unclaim.wolves: false
    adoptafuzz.free.item.*:
        description: Gives unclaims without consuming the item.
        default: false
        children:
            adoptafuzz.free.item.ocelots: false
            adoptafuzz.free.item.wolves: false
